[build]
  command = "NODE_ENV=production npm run build"
  publish = ".next"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = ["src/**"]

[functions."automations-cron"]
  schedule = "* * * * *"
