// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";
import { assertSupabaseDatabaseTarget } from "./src/lib/supabase/project-target";

config({ path: ".env.local" });
config({ path: ".env" });

const databaseUrl = process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"];
assertSupabaseDatabaseTarget({
  supabaseUrl: process.env["NEXT_PUBLIC_SUPABASE_URL"],
  databaseUrl,
});

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
