ALTER TYPE public."CommunityType" ADD VALUE IF NOT EXISTS 'RESTAURANT';
ALTER TYPE public."CommunityType" ADD VALUE IF NOT EXISTS 'CATERER';
ALTER TYPE public."CommunityType" ADD VALUE IF NOT EXISTS 'SPORT_COACH';
ALTER TYPE public."CommunityType" ADD VALUE IF NOT EXISTS 'COMMERCE';
ALTER TYPE public."CommunityType" ADD VALUE IF NOT EXISTS 'BUSINESS';
ALTER TYPE public."CommunityType" ADD VALUE IF NOT EXISTS 'CONTENT_CREATOR';
