"use client";

import Link from "next/link";
import { Check, ImageIcon, Sparkles } from "lucide-react";
import { useDemoState } from "./demo-state";

const VISUALS = [{ name: "Élégance bleue", style: "from-blue-950 via-blue-700 to-sky-400" }, { name: "Chaleur communautaire", style: "from-amber-500 via-orange-500 to-rose-600" }, { name: "Lumière de Chabbat", style: "from-violet-950 via-purple-700 to-amber-300" }];

export function DemoTemplatesClient() {
  const { state, selectVisual } = useDemoState();
  return <div className="space-y-5 pt-8"><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-blue-600">Parcours de démonstration · Étape 3</p><h1 className="mt-2 text-2xl font-bold text-slate-900">Choisir une affiche</h1><p className="mt-1 text-sm text-slate-500">Trois propositions préparées à partir de l’événement et de votre identité.</p></section><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{VISUALS.map((visual, index) => { const selected = state.visualSelected && index === 1; return <button key={visual.name} type="button" onClick={selectVisual} className={`overflow-hidden rounded-3xl border bg-white p-3 text-left shadow-sm transition hover:-translate-y-1 hover:shadow-lg ${selected ? "border-blue-500 ring-2 ring-blue-100" : "border-slate-200"}`}><div className={`relative aspect-[3/4] overflow-hidden rounded-2xl bg-gradient-to-br ${visual.style} p-5 text-white`}><Sparkles className="size-5" /><p className="mt-16 text-xs font-semibold uppercase tracking-[0.2em]">Beth Habad du Marais</p><p className="mt-3 text-2xl font-black">Grand Chabbat communautaire</p><p className="mt-3 text-sm">Vendredi · 19h30<br />21 rue des Rosiers</p><div className="absolute bottom-5 left-5 right-5 rounded-xl bg-white/15 p-3 text-xs backdrop-blur">Réservez votre place · Entrée libre</div>{selected && <span className="absolute right-3 top-3 flex size-8 items-center justify-center rounded-full bg-white text-blue-700"><Check className="size-4" /></span>}</div><p className="mt-3 flex items-center gap-2 text-sm font-bold text-slate-900"><ImageIcon className="size-4 text-blue-600" /> {visual.name}</p></button>; })}</div>{state.visualSelected && <div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-900"><span>Affiche sélectionnée et personnalisée.</span><Link href="/demo/social-networks" className="rounded-xl bg-emerald-700 px-4 py-2 text-xs text-white">Adapter aux réseaux →</Link></div>}</div>;
}
