/**
 * Shalom IA — Données de démonstration
 * Activé via NEXT_PUBLIC_DEMO_MODE=true
 * Simule une communauté "Beth Habad Paris Marais" avec données réalistes
 */

export const DEMO_MODE = process.env.NEXT_PUBLIC_DEMO_MODE === "true";

// ─── Profil utilisateur démo ───────────────────────────────────────────────
export const DEMO_PROFILE = {
  id: "demo-user-id",
  email: "demo@yad-ia.com",
  name: "Rabbi Lévi Cohen",
  avatarUrl: null,
  role: "ADMIN" as const,
  communityId: "demo-community-id",
  createdAt: new Date("2024-01-15"),
  updatedAt: new Date(),
  community: null,
  auditLogs: [],
  notifications: [],
};

// ─── Communauté démo ───────────────────────────────────────────────────────
export const DEMO_COMMUNITY = {
  id: "demo-community-id",
  name: "Beth Habad du Marais",
  slug: "beth-habad-marais",
  description: "Centre Loubavitch au cœur du Marais parisien, ouvert à tous.",
  logoUrl: null,
  coverUrl: null,
  city: "Paris",
  country: "France",
  timezone: "Europe/Paris",
  phone: "+33 1 42 72 01 90",
  email: "contact@bh-marais.fr",
  website: "https://www.bh-marais.fr",
  address: "21 Rue des Rosiers",
  postalCode: "75004",
  tone: "FRIENDLY" as const,
  language: "fr",
  signature: "— Beth Habad du Marais 🕯️",
  hashtags: ["#shabbat", "#bhmarais", "#paris4", "#judaisme", "#loubavitch"],
  mentions: ["@bhmarais"],
  editorialRules: "Toujours inclure les horaires précis du Chabbat. Utiliser 'Chabbat' et non 'Sabbat'. Ton chaleureux et inclusif.",
  vocabulary: { Chabbat: "Samedi saint", Havdala: "Fin du Chabbat" },
  communityType: "SYNAGOGUE" as const,
  religiousStream: "Loubavitch",
  plan: "PROFESSIONAL" as const,
  planExpiresAt: null,
  stripeCustomerId: null,
  onboardingDone: true,
  onboardingStep: 5,
  createdAt: new Date("2024-01-15"),
  updatedAt: new Date(),
};

// ─── Canaux démo ───────────────────────────────────────────────────────────
export const DEMO_CHANNELS = [
  { id: "ch-instagram", communityId: "demo-community-id", type: "INSTAGRAM" as const, name: "Instagram", handle: "@bhmarais", isConnected: true, isActive: true, accessToken: null, refreshToken: null, tokenExpiresAt: null, pageId: null, settings: null, lastSyncAt: new Date(), createdAt: new Date(), updatedAt: new Date() },
  { id: "ch-facebook", communityId: "demo-community-id", type: "FACEBOOK" as const, name: "Facebook", handle: "Beth Habad du Marais", isConnected: true, isActive: true, accessToken: null, refreshToken: null, tokenExpiresAt: null, pageId: "12345678", settings: null, lastSyncAt: new Date(), createdAt: new Date(), updatedAt: new Date() },
  { id: "ch-whatsapp", communityId: "demo-community-id", type: "WHATSAPP" as const, name: "WhatsApp", handle: null, isConnected: false, isActive: true, accessToken: null, refreshToken: null, tokenExpiresAt: null, pageId: null, settings: null, lastSyncAt: null, createdAt: new Date(), updatedAt: new Date() },
  { id: "ch-telegram", communityId: "demo-community-id", type: "TELEGRAM" as const, name: "Telegram", handle: "@bhmarais_official", isConnected: true, isActive: true, accessToken: null, refreshToken: null, tokenExpiresAt: null, pageId: "-1001234567890", settings: null, lastSyncAt: new Date(), createdAt: new Date(), updatedAt: new Date() },
  { id: "ch-email", communityId: "demo-community-id", type: "EMAIL" as const, name: "Email", handle: null, isConnected: true, isActive: true, accessToken: null, refreshToken: null, tokenExpiresAt: null, pageId: null, settings: null, lastSyncAt: new Date(), createdAt: new Date(), updatedAt: new Date() },
];

// ─── Événements démo ───────────────────────────────────────────────────────
const now = new Date();
const nextFriday = new Date(now);
nextFriday.setDate(now.getDate() + ((5 - now.getDay() + 7) % 7 || 7));
nextFriday.setHours(18, 30, 0, 0);

export const DEMO_EVENTS = [
  {
    id: "evt-shabbat-1",
    communityId: "demo-community-id",
    title: "Office de Chabbat",
    description: "Office de Chabbat Parachat Vayéra. Accueil 30 min avant l'allumage. Kiddouch convivial après l'office.",
    startDate: nextFriday,
    endDate: new Date(nextFriday.getTime() + 2 * 60 * 60 * 1000),
    location: "Grande salle de prière",
    address: "21 Rue des Rosiers, Paris 75004",
    category: "SHABBAT" as const,
    audience: "Toute la communauté",
    status: "READY" as const,
    isRecurring: true,
    recurrenceRule: null,
    parentEventId: null,
    coverImageUrl: null,
    isPublic: true,
    maxAttendees: null,
    registrationUrl: null,
    notes: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "evt-cours-1",
    communityId: "demo-community-id",
    title: "Cours de Tanya — Chapitre 32",
    description: "Étude approfondie du Tanya avec le Rabbin. Accessible à tous les niveaux.",
    startDate: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000),
    endDate: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000 + 90 * 60 * 1000),
    location: "Salle d'étude",
    address: "21 Rue des Rosiers, Paris 75004",
    category: "COURSE" as const,
    audience: "Adultes",
    status: "PUBLISHED" as const,
    isRecurring: false,
    recurrenceRule: null,
    parentEventId: null,
    coverImageUrl: null,
    isPublic: true,
    maxAttendees: 30,
    registrationUrl: null,
    notes: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "evt-hanoucca",
    communityId: "demo-community-id",
    title: "Allumage public de Hanoukka — Place des Vosges",
    description: "Grand allumage de Hanoukka sur la Place des Vosges. Beignets, chants et jeux pour les enfants. Ouvert à tous !",
    startDate: new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000),
    endDate: new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000),
    location: "Place des Vosges",
    address: "Place des Vosges, Paris 75004",
    category: "HOLIDAY" as const,
    audience: "Grand public",
    status: "DRAFT" as const,
    isRecurring: false,
    recurrenceRule: null,
    parentEventId: null,
    coverImageUrl: null,
    isPublic: true,
    maxAttendees: 500,
    registrationUrl: null,
    notes: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "evt-jeunesse",
    communityId: "demo-community-id",
    title: "Afterwork Jeunesse",
    description: "Soirée conviviale pour les 20-35 ans. Présentation de la paracha de la semaine et débat.",
    startDate: new Date(now.getTime() + 4 * 24 * 60 * 60 * 1000),
    endDate: new Date(now.getTime() + 4 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000),
    location: "Salon communautaire",
    address: "21 Rue des Rosiers, Paris 75004",
    category: "YOUTH" as const,
    audience: "20-35 ans",
    status: "READY" as const,
    isRecurring: false,
    recurrenceRule: null,
    parentEventId: null,
    coverImageUrl: null,
    isPublic: true,
    maxAttendees: 50,
    registrationUrl: null,
    notes: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "evt-collecte",
    communityId: "demo-community-id",
    title: "Collecte de fonds — Rénovation de la salle",
    description: "Campagne de levée de fonds pour la rénovation de notre salle principale. Chaque don compte !",
    startDate: new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000),
    endDate: new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000),
    location: "En ligne",
    address: null,
    category: "FUNDRAISING" as const,
    audience: "Tous les sympathisants",
    status: "SCHEDULED" as const,
    isRecurring: false,
    recurrenceRule: null,
    parentEventId: null,
    coverImageUrl: null,
    isPublic: true,
    maxAttendees: null,
    registrationUrl: "https://don.bh-marais.fr",
    notes: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// ─── Brouillons de contenu démo ────────────────────────────────────────────
export const DEMO_DRAFTS = [
  {
    id: "draft-shabbat-1",
    communityId: "demo-community-id",
    eventId: "evt-shabbat-1",
    title: "Horaires Chabbat Vayéra",
    body: `🕯️ Chabbat Parachat Vayéra — Ce vendredi soir\n\nCher communauté,\n\nVoici les horaires pour ce magnifique Chabbat :\n\n✨ Allumage des bougies : 17h42\n🕍 Office du soir (Kabbalat Chabbat) : 18h00\n📖 Kiddouch & repas communautaire : 19h30\n\nSamedi :\n🌅 Chachrit : 09h30\n📚 Étude de la Paracha : 11h30\n🍷 Havdala : 18h58\n\nPour cette Paracha, le Rabbin commentera la rencontre d'Abraham avec les trois anges — un message intemporel d'hospitalité et de générosité.\n\nChabat Chalom à tous ! 🌟\n— Beth Habad du Marais 🕯️`,
    bodyHebrew: null,
    bodyEnglish: null,
    hashtags: ["#shabbat", "#bhmarais", "#paris4", "#judaisme", "#chabatchalom"],
    cta: "Rejoignez-nous vendredi soir !",
    imageUrl: null,
    imagePrompt: null,
    status: "READY_TO_PUBLISH" as const,
    contentType: "SHABBAT_TIMES" as const,
    aiGenerated: true,
    aiModel: "gemini-2.5-flash",
    aiPromptUsed: "Générer les horaires Chabbat pour Paris",
    version: 1,
    parentDraftId: null,
    scheduledAt: new Date(nextFriday.getTime() - 2 * 24 * 60 * 60 * 1000),
    publishedAt: null,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000),
    event: { title: "Office de Chabbat", category: "SHABBAT" },
    channelAdaptations: [
      { channelType: "INSTAGRAM", body: "🕯️ Chabbat Vayéra ce vendredi !\n\nAllumage à 17h42 | Office à 18h00\nKiddouch convivial à 19h30\n\nSamedi : Chachrit 9h30 • Havdala 18h58\n\nChabat Chalom ! 🌟", hashtags: ["#shabbat", "#bhmarais", "#paris"] },
      { channelType: "FACEBOOK", body: "🕯️ Chabbat Parachat Vayéra — Horaires & Programme\n\nVendredi soir, allumage à 17h42. Office à 18h00, suivi d'un kiddouch convivial.\n\nSamedi : Chachrit à 9h30, havdala à 18h58.\n\nLe Rabbin commentera la rencontre d'Abraham avec les trois anges. Chabat Chalom à tous ! 🌟", hashtags: ["#shabbat", "#bhmarais"] },
    ],
    publications: [
      { id: "pub-1", status: "SCHEDULED", channelType: "INSTAGRAM", publishedAt: null, scheduledAt: new Date(nextFriday.getTime() - 2 * 24 * 60 * 60 * 1000), externalUrl: null, fallbackUsed: false, channel: { type: "INSTAGRAM", name: "Instagram" } },
    ],
  },
  {
    id: "draft-cours-1",
    communityId: "demo-community-id",
    eventId: "evt-cours-1",
    title: null,
    body: `📚 Cours de Tanya — Chapitre 32\n\nLe Rabbin vous invite à une étude approfondie du chapitre 32 du Tanya ce mercredi à 20h00.\n\n"L'amour du prochain" — ce chapitre fondamental nous enseigne comment l'amour envers D.ieu et l'amour envers autrui sont intrinsèquement liés.\n\nAccessible à tous les niveaux. Venez comme vous êtes ! 📖\n\n📍 Salle d'étude — 21 Rue des Rosiers\n⏰ 20h00 — 21h30`,
    bodyHebrew: null,
    bodyEnglish: null,
    hashtags: ["#tanya", "#cours", "#bhmarais", "#etudejuive"],
    cta: "Réservez votre place",
    imageUrl: null,
    imagePrompt: null,
    status: "DRAFT" as const,
    contentType: "COURSE_ANNOUNCEMENT" as const,
    aiGenerated: false,
    aiModel: null,
    aiPromptUsed: null,
    version: 1,
    parentDraftId: null,
    scheduledAt: null,
    publishedAt: null,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    event: { title: "Cours de Tanya — Chapitre 32", category: "COURSE" },
    channelAdaptations: [],
    publications: [],
  },
  {
    id: "draft-hanoucca-1",
    communityId: "demo-community-id",
    eventId: "evt-hanoucca",
    title: "✨ Grand allumage de Hanoukka — Place des Vosges",
    body: `🕎 HANOUKKA EST ARRIVÉ !\n\nVenez célébrer avec nous le grand allumage public de Hanoukka sur la magnifique Place des Vosges !\n\n🗓️ Dans 2 semaines\n📍 Place des Vosges, Paris 75004\n⏰ 18h00 — entrée libre\n\nAu programme :\n🍩 Sufganiot (beignets) & latkes maison\n🎵 Chants traditionnels en famille\n🎠 Animation enfants avec cadeaux\n🕎 Allumage solennel de la Hanoukia géante\n\nCet événement est ouvert à TOUS — partagez autour de vous ! ❤️`,
    bodyHebrew: null,
    bodyEnglish: null,
    hashtags: ["#hanoucca", "#hanoukka", "#paris", "#bhmarais", "#fetedesfetes"],
    cta: "Partagez cet événement !",
    imageUrl: null,
    imagePrompt: null,
    status: "AI_PROPOSAL" as const,
    contentType: "HOLIDAY_GREETING" as const,
    aiGenerated: true,
    aiModel: "gemini-2.5-flash",
    aiPromptUsed: "Générer une annonce enthousiaste pour l'allumage de Hanoukka place des Vosges",
    version: 2,
    parentDraftId: null,
    scheduledAt: null,
    publishedAt: null,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 60 * 60 * 1000),
    event: { title: "Allumage public de Hanoukka", category: "HOLIDAY" },
    channelAdaptations: [],
    publications: [],
  },
];

// ─── Publications démo ─────────────────────────────────────────────────────
export const DEMO_PUBLICATIONS = [
  {
    id: "pub-published-1",
    communityId: "demo-community-id",
    eventId: "evt-shabbat-1",
    draftId: "draft-shabbat-1",
    channelId: "ch-instagram",
    channelType: "INSTAGRAM" as const,
    status: "PUBLISHED" as const,
    scheduledAt: null,
    publishedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    externalId: "17854321098765432",
    externalUrl: "https://www.instagram.com/p/demo123",
    content: "🕯️ Chabbat Vayéra — Office vendredi 18h00...",
    mediaUrls: [],
    metadata: null,
    error: null,
    retryCount: 0,
    fallbackUsed: false,
    fallbackType: null,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    channel: { type: "INSTAGRAM", name: "Instagram" },
    event: { title: "Office de Chabbat", category: "SHABBAT" },
    draft: { title: "Horaires Chabbat Vayéra", body: "🕯️ Chabbat Vayéra..." },
  },
  {
    id: "pub-scheduled-1",
    communityId: "demo-community-id",
    eventId: "evt-shabbat-1",
    draftId: "draft-shabbat-1",
    channelId: "ch-instagram",
    channelType: "INSTAGRAM" as const,
    status: "SCHEDULED" as const,
    scheduledAt: new Date(nextFriday.getTime() - 2 * 24 * 60 * 60 * 1000),
    publishedAt: null,
    externalId: null,
    externalUrl: null,
    content: "🕯️ Chabbat Parachat Vayéra — Ce vendredi soir...",
    mediaUrls: [],
    metadata: null,
    error: null,
    retryCount: 0,
    fallbackUsed: false,
    fallbackType: null,
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000),
    channel: { type: "INSTAGRAM", name: "Instagram" },
    event: { title: "Office de Chabbat", category: "SHABBAT" },
    draft: { title: "Horaires Chabbat Vayéra", body: "🕯️ Chabbat..." },
  },
  {
    id: "pub-fallback-1",
    communityId: "demo-community-id",
    eventId: "evt-shabbat-1",
    draftId: "draft-shabbat-1",
    channelId: "ch-whatsapp",
    channelType: "WHATSAPP" as const,
    status: "FALLBACK_READY" as const,
    scheduledAt: null,
    publishedAt: null,
    externalId: null,
    externalUrl: null,
    content: "🕯️ Chabbat Vayéra — Allumage 17h42 | Office 18h00 | Havdala 18h58. Chabat Chalom !",
    mediaUrls: [],
    metadata: { whatsappLink: "https://wa.me/?text=Chabbat+Vay%C3%A9ra" },
    error: null,
    retryCount: 0,
    fallbackUsed: true,
    fallbackType: "COPY_PASTE" as const,
    createdAt: new Date(Date.now() - 25 * 60 * 1000),
    updatedAt: new Date(Date.now() - 25 * 60 * 1000),
    channel: { type: "WHATSAPP", name: "WhatsApp" },
    event: { title: "Office de Chabbat", category: "SHABBAT" },
    draft: { title: "Horaires Chabbat Vayéra", body: "🕯️ Chabbat..." },
  },
  {
    id: "pub-failed-1",
    communityId: "demo-community-id",
    eventId: "evt-cours-1",
    draftId: "draft-cours-1",
    channelId: "ch-facebook",
    channelType: "FACEBOOK" as const,
    status: "FAILED" as const,
    scheduledAt: null,
    publishedAt: null,
    externalId: null,
    externalUrl: null,
    content: "📚 Cours de Tanya — Chapitre 32...",
    mediaUrls: [],
    metadata: null,
    error: "Token Facebook expiré. Reconnectez votre page dans les paramètres.",
    retryCount: 2,
    fallbackUsed: false,
    fallbackType: null,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    channel: { type: "FACEBOOK", name: "Facebook" },
    event: { title: "Cours de Tanya — Chapitre 32", category: "COURSE" },
    draft: { title: null, body: "📚 Cours de Tanya..." },
  },
];

// ─── Automatisations démo ──────────────────────────────────────────────────
export const DEMO_AUTOMATIONS = [
  {
    id: "auto-shabbat",
    communityId: "demo-community-id",
    eventId: null,
    name: "Publication Chabbat hebdomadaire",
    description: "Publie automatiquement les horaires et le programme chaque jeudi à 10h",
    trigger: "WEEKLY_SHABBAT" as const,
    triggerConfig: { day: "thursday", time: "10:00", timezone: "Europe/Paris" },
    actions: [{ type: "GENERATE_CONTENT", contentType: "SHABBAT_TIMES", channels: ["INSTAGRAM", "FACEBOOK", "TELEGRAM"] }],
    isActive: true,
    lastRunAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    nextRunAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    status: "ACTIVE" as const,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date(),
    event: null,
    runs: [
      { id: "run-1", automationId: "auto-shabbat", status: "SUCCESS" as const, startedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000), completedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000 + 15000), error: null, result: null, logsCount: 3, automation: { name: "Publication Chabbat hebdomadaire" } },
    ],
  },
  {
    id: "auto-event-reminder",
    communityId: "demo-community-id",
    eventId: "evt-hanoucca",
    name: "Rappel Hanoukka",
    description: "Envoie un rappel 3 jours avant l'allumage de Hanoukka",
    trigger: "BEFORE_EVENT" as const,
    triggerConfig: { daysBefore: 3, time: "09:00" },
    actions: [{ type: "GENERATE_CONTENT", contentType: "EVENT_REMINDER", channels: ["INSTAGRAM", "FACEBOOK", "WHATSAPP", "TELEGRAM"] }],
    isActive: true,
    lastRunAt: null,
    nextRunAt: new Date(Date.now() + 11 * 24 * 60 * 60 * 1000),
    status: "ACTIVE" as const,
    createdAt: new Date(),
    updatedAt: new Date(),
    event: { title: "Allumage public de Hanoukka", startDate: new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000) },
    runs: [],
  },
  {
    id: "auto-cours-reminder",
    communityId: "demo-community-id",
    eventId: null,
    name: "Rappel cours hebdomadaire",
    description: "Rappelle les cours du dimanche chaque samedi soir",
    trigger: "WEEKLY_SHABBAT" as const,
    triggerConfig: { day: "saturday", time: "20:00" },
    actions: [{ type: "GENERATE_CONTENT", contentType: "COURSE_ANNOUNCEMENT", channels: ["TELEGRAM", "WHATSAPP"] }],
    isActive: false,
    lastRunAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
    nextRunAt: null,
    status: "PAUSED" as const,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date(),
    event: null,
    runs: [
      { id: "run-2", automationId: "auto-cours-reminder", status: "FAILED" as const, startedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000), completedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000 + 5000), error: "Canal Telegram non configuré", result: null, logsCount: 1, automation: { name: "Rappel cours hebdomadaire" } },
    ],
  },
];

// ─── Notifications démo ────────────────────────────────────────────────────
export const DEMO_NOTIFICATIONS = [
  { id: "notif-1", userId: "demo-user-id", communityId: "demo-community-id", type: "AI_CONTENT_READY" as const, title: "Contenu IA prêt", body: "Votre post Chabbat Vayéra a été généré et est prêt à publier.", data: null, isRead: false, readAt: null, link: "/dashboard/content/draft-shabbat-1", createdAt: new Date(Date.now() - 30 * 60 * 1000) },
  { id: "notif-2", userId: "demo-user-id", communityId: "demo-community-id", type: "PUBLICATION_SUCCESS" as const, title: "Publication réussie", body: "Votre post Chabbat a été publié sur Instagram avec succès.", data: null, isRead: false, readAt: null, link: "/dashboard/publications", createdAt: new Date(Date.now() - 60 * 60 * 1000) },
  { id: "notif-3", userId: "demo-user-id", communityId: "demo-community-id", type: "PUBLICATION_FAILED" as const, title: "Échec de publication", body: "Token Facebook expiré. Reconnectez votre page dans les paramètres.", data: null, isRead: false, readAt: null, link: "/dashboard/settings/channels", createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000) },
  { id: "notif-4", userId: "demo-user-id", communityId: "demo-community-id", type: "AUTOMATION_TRIGGERED" as const, title: "Automatisation déclenchée", body: "L'automatisation Chabbat hebdomadaire s'est exécutée avec succès.", data: null, isRead: true, readAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), link: "/dashboard/automations", createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000) },
];

// ─── Stats démo ────────────────────────────────────────────────────────────
export const DEMO_STATS = {
  events: DEMO_EVENTS.length,
  published: 12,
  drafts: DEMO_DRAFTS.length,
  automations: DEMO_AUTOMATIONS.filter((a) => a.isActive).length,
};
